version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    assignees:
      - yamatt
    labels:
      - "dependabot"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    assignees:
      - yamatt
    labels:
      - "dependabot"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    assignees:
      - yamatt
    labels:
      - "dependabot"
