version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: hayel-server
    main: ./cmd/hayel-server
    binary: hayel-server
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
  - id: hayel-config
    main: ./cmd/hayel-config
    binary: hayel-config
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto
